<?php

/**
 * Implements hook_menu();
 */
function shady_playground_menu() {
  $items['shadyplayground/heartbeat'] = array(
      'page callback' => '_shadyplayground_heartbeat_update',
      'access arguments' => array('access content'),
  );
  return $items;
}

function _shadyplayground_heartbeat_update() {
  $result = db_query_range('
    SELECT uaid, variables, ha.nid, ha.uid, ha.nid_target, ha.cid, u.name, n.title
    FROM {heartbeat_activity} ha
    INNER JOIN {node} n ON ha.nid = n.nid
    INNER JOIN {users} u ON ha.uid = u.uid
    WHERE message_id = :message_id
    ', 0, 10, array(':message_id' => 'new_comment_report'));

  foreach ($result as $row) {
    if ($row->cid != 0) {
      $variables = heartbeat_decode_message_variables($row->variables);
      $comment = comment_load($row->cid);
      if (array_key_exists('!comment', $variables)) {
        $variables['!comment'] = check_markup($comment->comment_body[LANGUAGE_NONE][0]['value'], $comment->comment_body[LANGUAGE_NONE][0]['format']);
        db_query('UPDATE {heartbeat_activity} SET variables = :variables WHERE uaid = :uaid'
                , array(':variables' => heartbeat_encode_message_variables($variables), ':uaid' => $row->uaid));
      }
    }
  }
  return "Done!";
}
